###
GET http://localhost:7070/projects/3

###
GET http://localhost:7070/projects/myprojects/test

###
POST http://localhost:7070/projects/register
Content-Type: application/json;charset=UTF-8

{
  "accountId":"suyeon",
  "projectName":"project4",
  "projectExplain":"project is good",
  "projectStatus":"활성",
  "projectMemberIdList": [
    "user1",
    "user2",
    "user3"
  ]
}

###
POST http://localhost:7070/projects/register
Content-Type: application/json;charset=UTF-8

{
  "accountId":"suyeon",
  "projectName":"project4",
  "projectExplain":"project is good",
  "projectStatus":"활성"
}

###
PUT http://localhost:7070/projects/42
Content-Type: application/json;charset=UTF-8

{
  "accountId":"suyeon",
  "projectName":"project4",
  "projectExplain":"수정",
  "projectStatus":"활성",
  "projectMemberIdList": [
    "updateUser1",
    "updateUser2"
  ]
}

###
DELETE http://localhost:7070/projects/2

###
GET http://localhost:7070/