POST http://localhost:7070/tasks/register
Content-Type: application/json;charset=UTF-8

{
  "taskTitle": "두번째 업무",
  "taskContent": "화이팅",
  "project": {
    "projectId": 3,
    "accountId": "suyeon",
    "projectName": "project3",
    "projectExplain": "project is good",
    "projectStatus": "활성"
  },
  "accountId": "suyeon"
}

###
GET http://localhost:7070/tasks/3

###
PUT http://localhost:7070/tasks/6
Content-Type: application/json;charset=UTF-8

{
    "taskId": 6,
    "taskTitle": "네번째 업무",
    "taskContent": "수정해봅시다~!~!",
    "project": {
      "projectId": 3,
      "accountId": "suyeon",
      "projectName": "project3",
      "projectExplain": "project is good",
      "projectStatus": "활성",
      "projectMembers": []
    },
    "milestone": null,
    "accountId": "suyeon"
  }

###
DELETE http://localhost:7070/tasks/2