POST http://localhost:7070/tasks/register
Content-Type: application/json;charset=UTF-8

{
  "taskTitle": "태그와 마일스톤",
  "taskContent": "화이팅",
  "projectId": 3,
  "tagListId": [1, 2],
  "milestoneId": 21,
  "accountId": "suyeon"
}
### tag 없는 경우
POST http://localhost:7070/tasks/register
Content-Type: application/json;charset=UTF-8

{
  "taskTitle": "태그가 없음",
  "taskContent": "화이팅",
  "projectId": 3,
  "milestoneId": 1,
  "accountId": "suyeon"
}

### milestone없는 경우
POST http://localhost:7070/tasks/register
Content-Type: application/json;charset=UTF-8

{
  "taskTitle": "마일스톤 없음",
  "taskContent": "화이팅",
  "projectId": 3,
  "tagListId": [10, 11],
  "accountId": "suyeon"
}

### 둘 다 없는 경우
POST http://localhost:7070/tasks/register
Content-Type: application/json;charset=UTF-8

{
  "taskTitle": "태그와 마일스토 없는 경우",
  "taskContent": "화이팅",
  "projectId": 10,
  "accountId": "suyeon"
}

###
GET http://localhost:7070/tasks/3

###
PUT http://localhost:7070/tasks/33
Content-Type: application/json;charset=UTF-8

{
    "taskId": 33,
    "taskTitle": "네번째 업무",
    "taskContent": "수정해봅시다~!~!",
    "projectId": 3,
    "accountId": "suyeon"
  }

###
DELETE http://localhost:7070/tasks/2

###
GET http://localhost:7070/tasks/tags/13

###
GET http://localhost:7070/tasks/milestone/16