POST http://localhost:7070/tasks/register
Content-Type: application/json;charset=UTF-8

{
  "taskTitle": "테스크와 태크도 같이?!",
  "taskContent": "화이팅",
  "project": {
    "projectId": 3,
    "accountId": "suyeon",
    "projectName": "project3",
    "projectExplain": "project is good",
    "projectStatus": "활성"
  },
  "tagList": [
    {
      "tagId":1,
      "tagName": "NHN Academy",
      "project": {
        "projectId": 3,
        "accountId": "suyeon",
        "projectName": "project3",
        "projectExplain": "project is good",
        "projectStatus": "활성"
      }
    }, {
      "tagId":2,
      "tagName": "NHN Academy",
      "project": {
        "projectId": 3,
        "accountId": "suyeon",
        "projectName": "project3",
        "projectExplain": "project is good",
        "projectStatus": "활성"
      }
    }
  ],
  "milestone": {
    "milestoneId": 7,
    "milestoneName": "release3",
    "project": {
      "projectId": 3,
      "accountId": "suyeon",
      "projectName": "project3",
      "projectExplain": "project is good",
      "projectStatus": "활성",
      "projectMembers": []
    }
  },
  "accountId": "suyeon"
}

###
GET http://localhost:7070/tasks/3

###
PUT http://localhost:7070/tasks/6
Content-Type: application/json;charset=UTF-8

{
    "taskId": 6,
    "taskTitle": "네번째 업무",
    "taskContent": "수정해봅시다~!~!",
    "project": {
      "projectId": 3,
      "accountId": "suyeon",
      "projectName": "project3",
      "projectExplain": "project is good",
      "projectStatus": "활성",
      "projectMembers": []
    },
    "milestone": null,
    "accountId": "suyeon"
  }

###
DELETE http://localhost:7070/tasks/2

###
GET http://localhost:7070/tasks/tags/13

###
GET http://localhost:7070/tasks/milestone/16